### ISSUE TITLE
gen_captcha.py error

### ISSUE THREAD

**Issue by aloveric** [lindita/scrapy1688#1]
python info.py

Traceback (most recent call last):
  File "info.py", line 16, in <module>
    import prec
  File "/Users/xxx/Downloads/scrapy1688-master/prec.py", line 2, in <module>
    from gen_captcha import gen_captcha_text_and_image
  File "/Users/xxx/Downloads/scrapy1688-master/gen_captcha.py", line 15
SyntaxError: Non-ASCII character '\xe9' in file /Users/xxx/Downloads/scrapy1688-master/gen_captcha.py on line 15, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by lindita** [comment]
http://blog.csdn.net/u011845742/article/details/44831707
